# .github/workflows/deploy.yml
name: Deploy LinkedIn Assistant

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        # Refactored for Angular sub-folder and base-href
        run: npm run build -- --base-href /YOUR_REPO_NAME/ 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Fixed path for Angular 18+ output
          path: dist/client/browser 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4